name: Run Python script

on:
  schedule:
    - cron: '0 8-17/2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run updateExcel script
      run: python updateExcel.py

    - name: Run main script
      run: python main.py
      
    - name: Run thumbnails script
      run: python thumbnails.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'lbzepeda'
        git config --global user.email 'levi.zepeda06@gmail.com'
        git add -A
        timestamp=$(date -u)
        git commit -m "Automated update: ${timestamp}" || exit 0
        git push

